### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by NullPointer1331** [NullPointer1331/DnDesigner#34]
- Install Microsoft.EntityFrameworkCore.SqlServer, Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore, and Microsoft.EntityFrameworkCore.Tools using NuGet. 
- Make a DbContext class and add all of our classes to the context
- Use migrations to make the database

**Comment by JohnnyBee86** [comment]
Setting all DbSets to public
