### ISSUE TITLE
Character Sheet Notes and Health input limits Implementation

### ISSUE THREAD

**Issue by JohnnyBee86** [NullPointer1331/DnDesigner#75]
- [x] Set Min and Max limit for Current Health
- [x] Set Min limit for Temporary Health
- [x] #76

**Comment by NullPointer1331** [comment]
Currently the only actions in the database are from weapons, so if you want to test this properly you'd either have to test after the Inventory is properly implemented on the character sheet, or test it manually.

**Comment by JohnnyBee86** [comment]
@NullPointer1331 Or I might just adjust this issue to be Notes implementation and Action/Inventory design.  Unless that sounds too lazy?
